### ISSUE TITLE
Beginner looking for help!

### ISSUE THREAD

**Issue by TheSaltyLabs** [thomasperge/GoodFarm#1]
Hi,
I am very beginner to making discord bots and your code looks perfect as a starting place for me to make one! But I am completely lost on what even to do with the code! I was just wondering if you would be able to help at all or explain what I need to change to personalize the bot to what I want and what to use the code on to make the bot work?
Thank you,
Salty

**Comment by thomasperge** [comment]
Hi, 
No worries, you can use the code I put at your disposal.
First of all you have to create a discord bot via this link: https://discord.com/developers/docs/intro
I invite you to set it and its permissions.
The bot uses MongoDb for the database, you must create an account here: https://www.mongodb.com/, and configure your account.
As you can see there is a .gitignore file, which hides the config.json file.
You just have to create the config.json file:
- config.json:
```
{
  "prefix": "g",
  "idServerOfficial": "707134426517078038",
  "token": "The token of your bot",
  "mongodb": "The MongoDb cloud recovery link you created",
  "idLog1": "888769452160712704",
  "idLogM": "888769854969118730",
  "idLogF": "888769924456153158"
}
```

**Comment by TheSaltyLabs** [comment]
Ok Thank you so much For the help I’m sure I’ll have other issues but that helps me get started!! I mainly Make emojis and logos but I also run a discord community that has lots of different bots. And I was thinking I could make a really fun gaming/economy bot! You are really awesome for letting others use your code! I would be no where without it!

**Comment by TheSaltyLabs** [comment]
Oh also in the code where you have the emojis, do you have those emojis in the same discord server the bot is created in or do you just paste emojis from any discord server?

**Comment by thomasperge** [comment]
Emojis work, I created a special discord server for emojis.
If you have any other questions don't hesitate on discord: elthomas#2246
